config/routes.rb
SoupExchange::Application.routes.draw do
  

  resources :soups
  resources :users

  match 'soups/:id' => 'soups#show'

  get "static_pages/home"
  root :to => "static_pages#home" 

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', :via => :delete

end

app/models/soup.rb
class Soup < ActiveRecord::Base
  attr_accessible :ingredients, :recipe, :title
  validates :title, presence: true
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :soups
  #belongs_to:week
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token


  validates :name, presence: true,
  			length: {minimum: 4, maximum: 50}
  			
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  			format: {with: VALID_EMAIL_REGEX},
  			uniqueness: {case_sensative: false}

  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true

private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/week.rb
# == Schema Information
#
# Table name: weeks
#
#  id         :integer         not null, primary key
#  date_start :date
#  date_end   :date
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Week < ActiveRecord::Base
  attr_accessible :date_end, :date_start
  has_many:users
  has_many:soups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
      sign_in user
    	redirect_to user
  	else
    	flash.now[:notice] = 'Invalid email/password combination' # Not quite right!
      render 'new'
  	end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
	before_filter :signed_in_user
	def new
		@soup = Soup.new
	end

	def create
		@soup = current_user.soups.create(params[:soup])
		if @soup.save
      		redirect_to(@soup, :notice => "You saved a soup #{current_user.name}")
		end
	end

	def edit 
		@soup = Soup.find(params[:id])
	end 

	def update
		@soup = Soup.find(params[:id])
		@soup.update_attributes(params[:soup])
		redirect_to(@soup)
	end

	def show
		@soup = Soup.find(params[:id])
	end

	def destroy
		@soup = Soup.find(params[:id])
		@soup.destroy
		redirect_to(root_path, :notice => "You deleted #{@soup.title}")
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	Soup.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :signed_in_user, only: [:edit, :update]

  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
		if @user.save
      		redirect_to(@user, :notice => "Welcome to the Soup Exchange!")
      	else 
      		redirect_to(new_user_path, :notice => @user.errors.full_messages)
		end
  end

  def show
  	@user = User.find(params[:id])
    @soups = @user.soups
  end
  
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

 def current_user=(user)
  @current_user = user
 end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/soups_helper.rb
module SoupsHelper

def create_unordered_list(list, style_class = nil )
		if list.empty?
		  
		else
			if style_class.empty?
				listString = "<ul>#{create_list(list)}</ul>"
				listString.html_safe
			else 
				listString = "<ul class=#{style_class}>#{create_list(list)}</ul>"
				listString.html_safe
			end

		end
	end

	def create_ordered_list(list, style_class = nil)
		if list.empty?
		
		else 
			if style_class.empty?
				listString = "<ol>#{create_list(list)}</ol>"
				listString.html_safe
			else 
				listString = "<ol class=#{style_class}>#{create_list(list)}</ol>"
				listString.html_safe
			end
		end
	end


	def create_list(stringList)
		arrayList = stringList.split(",")
		listString = ""
		arrayList.each do |n|
			listString += "<li>#{n}</li>"
		end
		listString
	end

	def list_alphabetical_soups(soupList)
		output="<ul id='list_of_soups'>"
		@soups=soupList.group_by{|soup| soup.title[0]}
		@soups.keys.sort.each do |starting_letter| 
			output += starting_letter
				@soups[starting_letter].each do |soup| 
					output += "<li>#{link_to(soup.title, soup_path(soup))}</li>"
				end
		end 
		output += "</ul>"
		output.html_safe
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
	
	
end

app/views/layouts/_nav.html.erb
<nav>
	<%= link_to("Home",root_path) %>
	<% if signed_in? %>
		<%= link_to("My Profile", current_user) %> 
	<% else %>
		<%= link_to("Sign In", signin_path) %>
	<% end %>
	
	<%= link_to("This Week", root_path) %> 
	<%= link_to("All Soups", soups_path) %> 
	<%= link_to("Add New soup ", new_soup_path) %>
	<% if signed_in? %>
		<%= link_to("Sign Out", signout_path, method: "delete") %> 
	<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoupExchange</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render 'layouts/nav' %> 

<% if signed_in? %>
	<p>Hello <%= current_user.name %></p>
<% else %>
	Not signed in 
<% end %>

<%= debug(params) if Rails.env.development? %>

<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/soups/edit.html.erb
<%= provide(:title, 'New Soup') %>

    <%= form_for(@soup) do |f| %>
         
      <%= f.label :title %>
      <%= f.text_field :title %>
     

      <%= f.label :ingredients %>
      <%= f.text_area :ingredients %>


      <%= f.label :recipe %>
      <%= f.text_area :recipe %>


      <%= f.submit "Save Recipe"%>
    <% end %>
  </div>
</div>

app/views/soups/index.html.erb
<%= list_alphabetical_soups(Soup.all) %>

app/views/soups/new.html.erb
<%= provide(:title, 'New Soup') %>

    <%= form_for(@soup) do |f| %>
         
      <%= f.label :title %>
      <%= f.text_field :title %>
     

      <%= f.label :ingredients %>
      <%= f.text_area :ingredients %>


      <%= f.label :recipe %>
      <%= f.text_area :recipe %>


      <%= f.submit "Create a New Recipe"%>
    <% end %>
  </div>
</div>

app/views/soups/show.html.erb
<% provide(:title, @soup.title) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @soup.title %>
      </h1>
      <h3> Ingredients </h3>
      <%= create_unordered_list(@soup.ingredients, 'ingredients') %>

      <h3> Directions </h3>
      <%= create_ordered_list(@soup.recipe, 'recipe') %>

      <%= link_to("Edit Soup", edit_soup_path(@soup)) %>
      <%= link_to("Delete Soup", @soup, :method => :delete) %>
    </section>
  </aside>
</div>

app/views/static_pages/home.html.erb
<h1>Welcome to the Soup Exchange</h1>
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
 <% end %>

 

app/views/users/new.html.erb
<%= provide(:title, 'New User') %>

    <%= form_for(@user) do |f| %>
         
      <%= f.label :name %>
      <%= f.text_field :name %>
     

      <%= f.label :email %>
      <%= f.text_field :email %>


      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Sign Up"%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<h2> <%= @user.email %> </h2>
<%= list_alphabetical_soups(@soups) %>